# ============================================================
# HR Platform - Spring Boot Configuration
# SQL Server: DESKTOP-D0KJLBA:1433 | DB: HRPlatformDB
# ============================================================

spring.application.name=hr-platform-backend

# --- SQL Server (Windows Authentication) ---
spring.datasource.url=jdbc:sqlserver://DESKTOP-D0KJLBA:1433;databaseName=HRPlatformDB;encrypt=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=12345

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# --- Server ---
server.port=8081
server.servlet.context-path=/api

# --- JWT ---
app.jwt.secret=HRPlatform2026SecretKeyForJWTTokenGenerationMustBe256BitsLong!
app.jwt.expiration=86400000

# --- File Upload ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.dir=./uploads

# --- CORS (Angular dev server) ---
app.cors.allowed-origins=http://localhost:4200

# --- Logging ---
logging.level.com.hrplatform=DEBUG
logging.level.org.springframework.security=WARN

# --- Email (SMTP - Gmail) ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=malekfitouri123@gmail.com
spring.mail.password=xasdbwiqabcguebl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
app.mail.from=malekfitouri123@gmail.com
app.mail.enabled=true
